name: Cleanup Old Recordings

on:
  schedule:
    - cron: '0 2 * * *' # ירוץ כל לילה ב-2 לפנות בוקר
  workflow_dispatch:

jobs:
  delete-old-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete releases older than 7 days
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 0
          older_than: 7d # מוודא מחיקה רק של מה שעבר עליו שבוע
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
